### ISSUE TITLE
[Bug] serde feature on meta-crate doesn't enable serde feature in alloy-rpc-types-* crates

### ISSUE THREAD

**Issue by morph-dev** [alloy-rs/alloy#1453]
### Component

meta-crate, serde

### What version of Alloy are you on?

0.4.2

### Operating System

Linux

### Describe the bug

The `serde` feature on `alloy` meta-crate doesn't enable `serde` feature in `alloy-rpc-types-*` crates.
The following code doesn't compile:

file: `Cargo.toml`
```toml
[dependencies]
alloy = { version = "0.4.2", features = ["serde", "rpc-types-eth"] }
serde = { version = "1.0.210", features = ["derive"] }
```
file: `lib.rs`
```rust
use alloy::rpc::types::Transaction;
use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct MyStruct {
    tx: Transaction,
}
```

Probably the first step would be to create `serde` feature in `alloy-rpc-types` that if enabled, would enable feature in underlying crates as well.
