### ISSUE TITLE
[Bug] Impossible to enable "derive" feature of "alloy-rlp" when using meta-crate

### ISSUE THREAD

**Issue by morph-dev** [alloy-rs/alloy#1454]
### Component

meta-crate

### What version of Alloy are you on?

0.4.2

### Operating System

Linux

### Describe the bug

The `derive` feature of `alloy-rlp` crate can't be enabled from `alloy` meta-crate.
The following code doesn't compile:

file: Cargo.toml
```toml
[dependencies]
alloy = { version = "0.4.2", features = ["rlp"] }
```
file: lib.rs
```rust
pub use alloy::rlp::RlpEncodable;

#[derive(RlpEncodable)]
pub struct MyStruct {
    pub number: u64,
}
```
