### ISSUE TITLE
[Bug] alloy-sol-macro-input v1.2.0 requires unstable edition2024 feature, preventing compilation on stable Rust

### ISSUE THREAD

**Issue by vincentes** [alloy-rs/alloy#2562]
### Component

other

### What version of Alloy are you on?

alloy v1.0.1 

### Operating System

macOS (Apple Silicon)

## Bug Description
When trying to build a project with `alloy = { version = "1.0.1", features = ["essentials"] }`, cargo fails to download and compile `alloy-sol-macro-input v1.2.0` because it requires the unstable `edition2024` feature.

## Error Output
Error: failed to download alloy-sol-macro-input v1.2.0
Caused by:
unable to get packages from source
Caused by:
failed to parse manifest at /Users/vincxntes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-sol-macro-input-1.2.0/Cargo.toml
Caused by:
feature edition2024 is required
The package requires the Cargo feature called edition2024, but that feature is not stabilized in this version of Cargo (1.83.0 (5ffbef321 2024-10-29)).
Consider trying a newer version of Cargo (this may require the nightly release).

## Reproduction Steps
1. Create a new Rust project
2. Add `alloy = { version = "1.0.1", features = ["essentials"] }` to Cargo.toml
3. Run `cargo build`

## Cargo.toml
```toml
[package]
name = "verify_sent_tx_prep"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "1.0.1", features = ["essentials"] }
tokio = { version = "1.45.1", features = ["full"] }
```

## Environment
- Cargo version: 1.83.0 (5ffbef321 2024-10-29)
- Rust version: stable
- OS: macOS (darwin 24.4.0)

## Expected Behavior
The project should compile successfully on stable Rust without requiring nightly features.

## Current Workaround
None found - even attempting to force older versions of `alloy-sol-macro-input` via patches fails.
